query MyProfile {
  myProfile {
    username
    creationDate
    gamesPlayed
    gamesWon
    totalScore
    bestScore
    games {
      idGame
      score
      status
      word {
        label
        difficulty
      }
    }
  }
}