mutation SaveGame($idWord: Int!, $status: String!, $errors: Int!, $usedHint: Boolean!) {
  saveGame(idWord: $idWord, status: $status, errors: $errors, usedHint: $usedHint) {
    idGame
    score
    status
  }
}